### ISSUE TITLE
SEGV_MAPERR error when changing allocation size of malloc function

### ISSUE THREAD

**Issue by fafok29** [WhiteBox-Systems/whitebox#15]
### What happened?

Actual behavior:

I have the following code snippet:
```
#include <stdlib.h>
char *malloc_test(int arg)
{
	char *ptr = malloc(arg * sizeof(char));

	for (int i = 0; i < arg - 1; i++) {
		ptr[i] = 'a';
	}
	ptr[arg] = '\0';

	return ptr;
}
```

Whitebox generated the following Function Caller

```
int arg = 0;

malloc_test(arg);
```

If I change the value of arg to 2 for example Whiitebox will print the following message

> SEGV_MAPERR - Address not mapped to object (..addr here...)

and Whitebox won't use the new value.

Also, subsequent changes of arg will print this to console in a loop, and Whitebox will become unresponsive.

> An error occurred:
>1. [2022-08-11 01:23:33]: debug error: can't continue threads
>    dbg_event_next (../app_linux.c:839)
>2. [2022-08-11 01:23:33]: Linux error: E3: No such process
>   PTRACE_CONT (linux.h:0)

After restart, Whitebox uses the last arg value (I guess it was cached in whitebox.db) => it will work, until you change it again. So, basically, you can only specify malloc size once and need to restart Whitebox if you want to test with a different value.

Expected behavior:

I should be able to experiment with different malloc size arguments without the need to restart Whitebox.

https://user-images.githubusercontent.com/23638076/184036973-fee11f90-f395-493c-966a-cc15e8ec8618.mp4

### System/app details

WhiteBox version - 0.91.1
WhiteBox commit  - a1735eaf840395556371fae40ad42c7c39b2d4a8
Assert level     - 5
Debug info       - false
Kernel           - Linux 5.15.0-46-generic
OS               - Ubuntu 22.04.1 LTS
Architecture     - x86-64
CPU name         - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
CPU count        - 8
CPU MHz          - <unknown>
RAM              - 16G

### How to reproduce the error

Steps to reproduce:
  1. Start Whitebox
  2. Open code in vim
  3. connect to Whitebox
  4. Place cursor over malloc call
  5. In the Function Caller window of Whitebox, change the value of arg to 10
  6. At the bottom of Whitebox observe an orange line with the message: SEGV_MAPPER .....
  7. Now try to change the value of arg again to 5
  8. Whitebox is unresponsive + errors in the console
  ...

Does the error happen consistently with the above steps?
Always

Minimal reproducible code example:
```
#include <stdlib.h>
char *malloc_test(int arg)
{
	char *ptr = malloc(arg * sizeof(char));

	for (int i = 0; i < arg - 1; i++) {
		ptr[i] = 'a';
	}
	ptr[arg] = '\0';

	return ptr;
}
```

### Crash/log attachments & additional info

- whitebox-log.txt file is empty

- console output is

> edits to compile and jit for malloc_test... successful
> An error occurred: <<< this part printed in a loop
> 1. [2022-08-11 01:38:15]: debug error: can't continue threads
>      dbg_event_next (../app_linux.c:839)
> 2. [2022-08-11 01:38:15]: Linux error: E3: No such process
>     PTRACE_CONT (linux.h:0)

**Comment by azmr** [comment]
Thanks for the detailed bug reports @fafok29, I'll look into them today

**Comment by azmr** [comment]
Fixed in `e72030c` ready for next release

**Comment by fafok29** [comment]
When is next release?

**Comment by azmr** [comment]
@fafok29 hopefully tomorrow, unless there are unforeseen issues

**Comment by fafok29** [comment]
Great, is there a way to subscribe for release notification?

**Comment by azmr** [comment]
@fafok29 There's a button on the top-right of the itch page to follow us: https://azmr.itch.io/whitebox. You should get notifications from that on releases.

We also have a mailing list that you can sign up for: http://eepurl.com/gXDE3n

**Comment by azmr** [comment]
@fafok29 oh, and if you're not already on the Discord server, you can join through https://chat.whitebox.systems 😄

**Comment by fafok29** [comment]
Great, thank you
