### ISSUE TITLE
 Object files compiled with clang on windows are not recognized by whitebox

### ISSUE THREAD

**Issue by creikey** [WhiteBox-Systems/whitebox#18]
### What happened?

Actual behaviour:
`JIT Error: Symbols not found: [ addstwo ]`
Expected behaviour:
Works

### System/app details

(separate bug, the config details said I was on windows 10 instead of windows 11)

WhiteBox version - 0.99.0
WhiteBox commit  - afbcb9e50b23193969c379c791312efb5ed0b697
Assert level     - 1
Debug info       - false
OS               - Windows 11 Home x64 (10.0.22000)
Service pack     - (0.0)
CPU              - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Logical cores    - 8
CPU revision     - 0x9e09
RAM              - 15.9 GiB
Address space    - 128.0 TiB

### How to reproduce the error

Steps to reproduce:
  1. Put cursor inside of simplefunc() in `simple.c`

Does the error happen consistently with the above steps?
Always

Minimal reproducible code example:

simple.c:
```c
#include <stdio.h>

int addstwo(int number);

int simplefunc()
{
    int result = addstwo(5);

    printf("%d\n", result);
}
```

external.c:
```c
int addstwo(int number)
{
	return number + 2;
}
```
external.c is compiled like this:
`clang -target x86_64-pc-windows-elf -c external.c`
With this version info:
```
clang version 15.0.4
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

The compiled object file is added to whitebox like this:
![image](https://user-images.githubusercontent.com/28424206/209232972-11788161-6eb7-47ca-bb09-e13a20579a45.png)

### Crash/log attachments & additional info

Here is my external.c object file:
[external.zip](https://github.com/WhiteBox-Systems/whitebox/files/10290626/external.zip)

**Comment by azmr** [comment]
Thanks for the report and minimal example.

I added your `.o` file to the object files list and opened up your code but it worked fine: 
![image](https://user-images.githubusercontent.com/5575948/209240079-c967b209-84e4-44f5-93d5-f435a7b20d52.png)

I can't see from your preferences screenshot: is the object in the `Object files` tab or the `DLL files` tab? It being in the wrong place is currently my best guess, otherwise this might be a bit hairy!

Cheers,
Andrew

**Comment by creikey** [comment]
> Thanks for the report and minimal example.
> 
> I added your `.o` file to the object files list and opened up your code but it worked fine: ![image](https://user-images.githubusercontent.com/5575948/209240079-c967b209-84e4-44f5-93d5-f435a7b20d52.png)
> 
> I can't see from your preferences screenshot: is the object in the `Object files` tab or the `DLL files` tab? It being in the wrong place is currently my best guess, otherwise this might be a bit hairy!
> 
> Cheers, Andrew



> clang -target x86_64-pc-windows-elf -c external.c

I figured out why it wasn't working! It was something else random in my config that made whitebox early out or something like that, I deleted my entire config and made a fresh new one then added the object file and it works. Thanks for confirming on your end that my setup should've been working!

**Comment by azmr** [comment]
Ah great, thanks!

Is it something I should be aware of? Is there some sort of notification that would have been helpful?

**Comment by creikey** [comment]
> 

It seems like there isn't feedback on many issues in the whitebox config, like if an object file  can't be found on a given path. It just says it can't find the symbols still and is silent about specifically what the problem is in the config
