### ISSUE TITLE
Functions not detected correctly when definition starts with a macro

### ISSUE THREAD

**Issue by khvorov45** [WhiteBox-Systems/whitebox#23]
### What happened?

Actual behaviour:
"No function found under cursor"

Expected behaviour:
Expected the function to be, in fact, found under cursor.

### System/app details

WhiteBox version - 0.99.0
WhiteBox commit  - afbcb9e50b23193969c379c791312efb5ed0b697
Assert level     - 1
Debug info       - false
OS               - Windows 10 Pro x64 (10.0.19045)
Service pack     - (0.0)
CPU              - AMD Ryzen 9 7900 12-Core Processor             
Logical cores    - 24
CPU revision     - 0x6102
RAM              - 63.1 GiB
Address space    - 128.0 TiB

### How to reproduce the error

Steps to reproduce:
  1. Paste the code into a file and place the cursor inside the function

Does the error happen consistently with the above steps?
  Always

Minimal reproducible code example:
```c
#define function static
function void 
temp(void) {
    int x = 1;
}
```

### Crash/log attachments & additional info

Note that `bool` is a macro so this has the same problem

```c
#include <stdbool.h>
bool
temp(void) {
    int x = 1;
    return false;
}
```

But this works fine

```c
#include <stdbool.h>
static bool
temp(void) {
    int x = 1;
    return false;
}
```

**Comment by azmr** [comment]
Thanks for the report. This is already fixed ready for the next release 😀
