### ISSUE TITLE
de-emphasis stacks when editing while compiler is paused

### ISSUE THREAD

**Issue by 1wsx10** [WhiteBox-Systems/whitebox#25]
### What happened?

Actual behaviour:
window goes grey twice, and it becomes hard to read

Expected behaviour:
window goes grey once, but you can still read the text

### System/app details

WhiteBox version - 0.116.0
WhiteBox commit  - f1608e879ad5475d95f44ff2cc4d5cd22477afc8
Assert level     - 1
Debug info       - false
Kernel           - Linux 6.4.10-arch1-1
OS               - Arch Linux
Architecture     - x86-64
CPU name         - 11th Gen Intel(R) Core(TM) i7-11700B @ 3.20GHz
CPU count        - 16
CPU MHz          - <unknown>
RAM              - 16G

### How to reproduce the error

Steps to reproduce:
  1. use the vim plugin
  2. start a trace
  3. pause the compiler
  4. in vim, open another file and start editing
  ...

Does the error happen consistently with the above steps?
  [Always.]

Minimal reproducible code example:
  NA.

### Crash/log attachments & additional info

- not a crash

Any additional information/comments:

**Comment by azmr** [comment]
Thanks for the heads-up

**Comment by azmr** [comment]
Fixed in `376df85`
