### ISSUE TITLE
crash when using a VLA

### ISSUE THREAD

**Issue by 1wsx10** [WhiteBox-Systems/whitebox#26]
### What happened?

Actual behaviour:
it crashes

Expected behaviour:
i see a trace of the function

### System/app details

WhiteBox version - 0.116.0
WhiteBox commit  - f1608e879ad5475d95f44ff2cc4d5cd22477afc8
Assert level     - 1
Debug info       - false
Kernel           - Linux 6.4.10-arch1-1
OS               - Arch Linux
Architecture     - x86-64
CPU name         - 11th Gen Intel(R) Core(TM) i7-11700B @ 3.20GHz
CPU count        - 16
CPU MHz          - <unknown>
RAM              - 16G

### How to reproduce the error

Steps to reproduce:
  1. load this file
  2. change compiler settings from `-isystem` to `-I`
  3. position cursor on `interpAll`
  ...

Does the error happen consistently with the above steps?
  [Always]

Minimal reproducible code example:
```
#include <cmath>

struct RGB
{
	float r;
	float g;
	float b;
};

float distance(RGB a, RGB b)
{
	a.r -= b.r;
	a.g -= b.g;
	a.b -= b.b;

	return sqrt(a.r*a.r+a.b*a.b+a.g+a.g);
};

struct aoeu
{
	RGB c;
	float v;
};
float interpAll(RGB colour, aoeu *allPoints, size_t sz)
{
	double distances[sz];
	double weights[sz];
	double totalDistance = 0;
	float ret = {};


	for (int i = 0; i < sz; i++)
	{
		auto d = distance(colour, allPoints[i].c);
		totalDistance += d;
		distances[i] = d;
	}

	for (int i = 0; i < sz; i++)
		weights[i] = (totalDistance - distances[i]) / ((sz-1) * totalDistance);

	for (int i = 0; i < sz; i++)
		ret = ret + allPoints[i].v * weights[i];

	return ret;
}

```

### Crash/log attachments & additional info

```
--------------------


edits to compile and jit for "interpAll(RGB, aoeu*, unsigned long)"... successful
Unhandled reference: 55 - count



Internal Error: DWARF

Assertion failed in `dwarf_read_dies` - /home/azmr/whitebox/dwarf.c(3714):
    !"TODO"
    last OS error => 0: Success


Trace/breakpoint trap hit in PID: 624697. Attach a debugger, hit 'x' to exit or 'c' to continue...
```

Any additional information/comments:

**Comment by 1wsx10** [comment]
not sure why, but a super minimal example doesn't hit the assert.

**Comment by azmr** [comment]
Thanks, added to the TODO list!
