### ISSUE TITLE
true visualised as false

### ISSUE THREAD

**Issue by 1wsx10** [WhiteBox-Systems/whitebox#27]
### What happened?

Actual behaviour:
'ret' variable is displayed as true, but the visualisation is coloured as though it's false
Expected behaviour:

### System/app details

WhiteBox version - 0.116.0
WhiteBox commit  - f1608e879ad5475d95f44ff2cc4d5cd22477afc8
Assert level     - 1
Debug info       - false
Kernel           - Linux 6.5.3-arch1-1
OS               - Arch Linux
Architecture     - x86-64
CPU name         - 11th Gen Intel(R) Core(TM) i7-11700B @ 3.20GHz
CPU count        - 16
CPU MHz          - <unknown>
RAM              - 16G

### How to reproduce the error

Steps to reproduce:
  1. use the code example
  2. set this as the function caller
  ```
int len = 3;

for (int w = 0; w < len; w++)
{
  for (int r = 0; r < len; r++)
  {
    for (int tail = 0; tail < len; tail++)
       test(len, w, r, tail);
  }
}
```
  ...

Does the error happen consistently with the above steps?
Always

Minimal reproducible code example:
```
#include <stdint.h>
#include <stdbool.h>

bool test(int len, int w, int r, int tail)
{
	bool same = w == r;
	bool ret;
	bool tailGtRead = tail > r;
	bool tailLtWrit = tail < w;

	if (w > r)
	{
		ret = tailGtRead && tailLtWrit;
	}
	else
	{
		// r <= w
		ret = tailGtRead || tailLtWrit;
	}

	return ret;
}
```

### Crash/log attachments & additional info

- [ ] crash dump file (much smaller if (g)-zipped)
- [ ] whitebox-log.txt file

Any additional information/comments:

**Comment by azmr** [comment]
Thanks for the report.
I've tried to repro (on Ubuntu 20.04), but I'm not sure if I'm seeing what you are.

I saw 2 things that might be misinterpreted that I thought I'd clear up just in case:

1) bar chart rescaled by a large "true" bool value (here 127 - visible from tooltip, but I'll make it visible on the bar as well). This makes true & false look ~the same...
![image](https://github.com/WhiteBox-Systems/whitebox/assets/5575948/9afe52c4-9857-4329-923d-6a81a288675c)
2) bar for value that is only ever false is fully "on" as it is scaled to 1/range, i.e. 100% of the bar in this case.
![image](https://github.com/WhiteBox-Systems/whitebox/assets/5575948/a0b5c3e4-3cbb-4f7c-b063-6c56896cf02f)

Let me know if these do/don't address what you saw, and if not, please could you post a screenshot.
