### ISSUE TITLE
Freeze and crash when clicking on Run > "Working Directory" button

### ISSUE THREAD

**Issue by DerTee** [WhiteBox-Systems/whitebox#31]
### What happened?

Whitebox freezes instead of showing a file selection dialog when clicking on the Run > "Working Directory" button

### System/app details

sys_info:
WhiteBox version - 2024-10-22
WhiteBox commit  - 137532b2476839ab2ecc52324866745ec77ed0a8
Assert level     - 1
Debug info       - false
OS               - Windows 10 Home x64 (10.0.22631)
Service pack     - (0.0)
CPU              - AMD Ryzen 5 2600 Six-Core Processor            
Logical cores    - 12
CPU revision     - 0x802
RAM              - 16.0 GiB
Address space    - 128.0 TiB

### How to reproduce the error

Not reliably reproducible, sometimes the Windows directory selection dialog pops up as expected. Bug happens about 50% of the time
 1. Open whitebox_nightly-2024-10-22
 2. click on Run > Working Directory
 3. cursor switches to spinning and the application froze

### Crash/log attachments & additional info

No crash logs, because it was a freeze.

**Comment by azmr** [comment]
I've redone the folder dialog with the COM API, so hopefully this is fixed. Please let me know if it is when the next nightly goes out 😄

**Comment by DerTee** [comment]
It works fine now, thank you! 💯 
I've tried a couple of times, I'm fairly confident this is fixed for good :)
