### ISSUE TITLE
Crash(es) when moving mouse over timeline while debugging running program

### ISSUE THREAD

**Issue by DerTee** [WhiteBox-Systems/whitebox#33]
### What happened?

Whitebox crashes when I move my mouse cursor over the timeline while debugging a running program. I don't know which type of block is causing the problem because it happens too fast.

### System/app details

sys_info:
WhiteBox version - 2024-10-22
WhiteBox commit  - 137532b2476839ab2ecc52324866745ec77ed0a8
Assert level     - 1
Debug info       - false
OS               - Windows 10 Home x64 (10.0.22631)
Service pack     - (0.0)
CPU              - AMD Ryzen 5 2600 Six-Core Processor            
Logical cores    - 12
CPU revision     - 0x802
RAM              - 16.0 GiB
Address space    - 128.0 TiB

### How to reproduce the error

Steps to reproduce:
  1. Set up Run > Executable and Working directory
  2. Run the application
  3. search for a function to debug, and click the curly braces button -> this works, but:
    1. clicking on the "break"-button causes a crash
    2. clicking the curly braces button **before** running the application causes a crash `Assertion failed in ' Arr_get'  - common.c(56):    i < hdr->n    last OS error => 122: The data area passed to a system call is too small.` 
  4. move the mouse over the timeline -> crash, seems like a problem when trying to show a code snippet

```
[INFO ] --- [2024-10-28 20:15:51] [main.odin:298:initialize_sdl()] SDL2 init of subsystems timer, video, audio, events successful
[INFO ] --- [2024-10-28 20:15:51] [main.odin:301:initialize_sdl()] Using audiodriver wasapi
[INFO ] --- [2024-10-28 20:15:51] [main.odin:303:initialize_sdl()] Using videodriver windows
[INFO ] --- [2024-10-28 20:15:52] [main.odin:319:initialize_sdl()] SDL2 window creation successful
[INFO ] --- [2024-10-28 20:15:52] [main.odin:326:initialize_sdl()] SDL2 renderer creation successful
[INFO ] --- [2024-10-28 20:15:52] [main.odin:330:initialize_sdl()] RendererInfo{name = "direct3d", flags = RendererFlags{ACCELERATED, PRESENTVSYNC, TARGETTEXTURE}, num_texture_formats = 3, texture_formats = [372645892, 842094169, 1448433993, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], max_texture_width = 16384, max_texture_height = 16384}

Internal Error:

Assertion failed in `gui_snippet` - gui_wnds.c(120):
    line
    last OS error => 996: Overlapped I/O event is not in a signaled state.
Rich assert failed (hr: 0x80004005, comctl: 00007FFB72890000, TDI: 0000000000000000), using fallback...
```
Does the error happen consistently with the above steps?
Always

Minimal reproducible code example:
This is not happening in a C program, but in an Odin program.
[whitebox-2024-10-28-20-15-19.dmp.gz](https://github.com/user-attachments/files/17548596/whitebox-2024-10-28-20-15-19.dmp.gz)

[whitebox.log](https://github.com/user-attachments/files/17548589/whitebox.log)

### Crash/log attachments & additional info

- [X] crash dump file (much smaller if (g)-zipped)
- [X] whitebox-log.txt file

**Comment by azmr** [comment]
Fixed the title issue in `cc892f64` - just an overzealous assert.
I think I've also fixed the assert box, so you should be able to ignore this kind of issue in future...
