### ISSUE TITLE
Crash when clicking "Clear Data" while debugging executable during pause

### ISSUE THREAD

**Issue by DerTee** [WhiteBox-Systems/whitebox#34]
### What happened?

Whitbox crashes when clicking "Clear Data" while debugging executable during pause

### System/app details

sys_info:
WhiteBox version - 2024-10-29
WhiteBox commit  - 2e1709c2644e4e56ef1664f35e478d0ccda682cc
Assert level     - 1
Debug info       - false
OS               - Windows 10 Home x64 (10.0.22631)
Service pack     - (0.0)
CPU              - AMD Ryzen 5 2600 Six-Core Processor            
Logical cores    - 12
CPU revision     - 0x802
RAM              - 16.0 GiB
Address space    - 128.0 TiB

### How to reproduce the error

Steps to reproduce:
  1. setup a compiled binary to run
  2. choose a function to sample
  3. run executable (timeline fills up, everything works fine)
  4. pause the run
  5. clear data because I found that I don't need that data -> CRASH

Does the error happen consistently with the above steps?
Only happened once and got a different crash freeze while trying to reproduce (see issue #35 )
But I did manage to crash whitebox again by repeatedly running, pausing, clearing data and pausing again.

### Crash/log attachments & additional info

- [X] crash dump file (much smaller if (g)-zipped)

[whitebox-2024-10-31-09-29-12.dmp.gz](https://github.com/user-attachments/files/17586025/whitebox-2024-10-31-09-29-12.dmp.gz)

**Comment by azmr** [comment]
Fixed for next nightly in `db0227e7`
