### ISSUE TITLE
Freeze and crash when continuing a paused run while debugging executable

### ISSUE THREAD

**Issue by DerTee** [WhiteBox-Systems/whitebox#35]
### What happened?

Whitebox freezes and then crashes when continuing a paused run while debugging an executable. There is no error/assert and no automatic dump.

### System/app details

sys_info:
WhiteBox version - 2024-10-29
WhiteBox commit  - 2e1709c2644e4e56ef1664f35e478d0ccda682cc
Assert level     - 1
Debug info       - false
OS               - Windows 10 Home x64 (10.0.22631)
Service pack     - (0.0)
CPU              - AMD Ryzen 5 2600 Six-Core Processor            
Logical cores    - 12
CPU revision     - 0x802
RAM              - 16.0 GiB
Address space    - 128.0 TiB

### How to reproduce the error

Steps to reproduce:
  1. setup executable to run
  2. choose a function to sample
  3. run executable (timeline fills up, everything works fine)
  4. pause the run
  5. click run to continue -> Freeze and crash

Does the error happen consistently with the above steps?
Only happened once so far, could not reproduce yet.

### Crash/log attachments & additional info

procdump file sent via Discord because it is too big

Note to self: Captured using `procdump.exe -ma -h 5600 whitebox_freeze_during_rerun`

**Comment by azmr** [comment]
It wasn't an exact repro, but I fixed a user-proc multithreading issue that occurs in this scenario, which seems to possibly match the inconsistency you were finding.
I'm going to close this for now. Please reopen if you see it again.
